export const CREATE_BAKERY_REQUEST = "CREATE_BAKERY_REQUEST"
export const CREATE_BAKERY_SUCCESS = "CREATE_BAKERY_SUCCESS"
export const CREATE_BAKERY_FAILURE = "CREATE_BAKERY_FAILURE"

export const GET_BAKERY_REQUEST = "GET_BAKERY_REQUEST"
export const GET_BAKERY_SUCCESS = "GET_BAKERY_SUCCESS"
export const GET_BAKERY_FAILURE = "GET_BAKERY_FAILURE"
