export const UPDATE_CHEF_PROFILE_REQUEST = "UPDATE_CHEF_PROFILE_REQUEST"
export const UPDATE_CHEF_PROFILE_SUCCESS = "UPDATE_CHEF_PROFILE_SUCCESS"
export const UPDATE_CHEF_PROFILE_FAILURE = "UPDATE_CHEF_PROFILE_FAILURE"